### ISSUE TITLE
Windows version still causes a crash

### ISSUE THREAD

**Issue by manicogaming** [SAZONISCHE/modelch#8]
Windows version of modelch still causes the server to crash after the latest update.

**Comment by manicogaming** [comment]
You updated the extension but didn't compile it, how can I compile it?

**Comment by ianlucas** [comment]
FWIW I think it would be also useful to share how to update these values (gamedata for Windows and Linux) whenever we have a breaking update so that the community can also help update them.

**Comment by sazonische** [comment]
Up
https://github.com/sazonische/modelch/tree/master/build/package/addons/sourcemod/extensions
